/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBattleRouteImport } from './routes/_authenticated/battle'
import { Route as AuthenticatedChallengeRouteImport } from './routes/_authenticated/challenge'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTodoRouteImport } from './routes/_authenticated/todo'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminChaptersRouteImport } from './routes/_authenticated/admin/chapters'
import { Route as AuthenticatedAdminDemandsRouteImport } from './routes/_authenticated/admin/demands'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin/quizzes'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as AuthenticatedAdminStoreRouteImport } from './routes/_authenticated/admin/store'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin/subjects'
import { Route as AuthenticatedAdminTopicsRouteImport } from './routes/_authenticated/admin/topics'
import { Route as AuthenticatedAdminTrackingRouteImport } from './routes/_authenticated/admin/tracking'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as AuthenticatedPSlugRouteImport } from './routes/_authenticated/p.$slug'
import { Route as AuthenticatedTopicsIndexRouteImport } from './routes/_authenticated/topics/index'
import { Route as AuthenticatedTopicsTopicIdRouteImport } from './routes/_authenticated/topics/$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBattleRoute = AuthenticatedBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengeRoute = AuthenticatedChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodoRoute = AuthenticatedTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminChaptersRoute =
  AuthenticatedAdminChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDemandsRoute =
  AuthenticatedAdminDemandsRouteImport.update({
    id: '/demands',
    path: '/demands',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoreRoute = AuthenticatedAdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTopicsRoute =
  AuthenticatedAdminTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTrackingRoute =
  AuthenticatedAdminTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPSlugRoute = AuthenticatedPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsIndexRoute =
  AuthenticatedTopicsIndexRouteImport.update({
    id: '/topics/',
    path: '/topics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTopicsTopicIdRoute =
  AuthenticatedTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/battle': typeof AuthenticatedBattleRoute
  '/challenge': typeof AuthenticatedChallengeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/games': typeof AuthenticatedGamesRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/todo': typeof AuthenticatedTodoRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/admin/demands': typeof AuthenticatedAdminDemandsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/p/$slug': typeof AuthenticatedPSlugRoute
  '/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/topics/': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/battle': typeof AuthenticatedBattleRoute
  '/challenge': typeof AuthenticatedChallengeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/games': typeof AuthenticatedGamesRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/todo': typeof AuthenticatedTodoRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/admin/demands': typeof AuthenticatedAdminDemandsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/p/$slug': typeof AuthenticatedPSlugRoute
  '/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/topics': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/battle': typeof AuthenticatedBattleRoute
  '/_authenticated/challenge': typeof AuthenticatedChallengeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/todo': typeof AuthenticatedTodoRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/_authenticated/admin/demands': typeof AuthenticatedAdminDemandsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/store': typeof AuthenticatedAdminStoreRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/_authenticated/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/p/$slug': typeof AuthenticatedPSlugRoute
  '/_authenticated/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/topics/': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/achievements'
    | '/activity'
    | '/battle'
    | '/challenge'
    | '/dashboard'
    | '/downloads'
    | '/emergency'
    | '/flashcards'
    | '/games'
    | '/memory'
    | '/notes'
    | '/practice'
    | '/quizzes'
    | '/resources'
    | '/settings'
    | '/todo'
    | '/tracker'
    | '/videos'
    | '/admin/chapters'
    | '/admin/demands'
    | '/admin/events'
    | '/admin/members'
    | '/admin/questions'
    | '/admin/quizzes'
    | '/admin/resources'
    | '/admin/store'
    | '/admin/subjects'
    | '/admin/topics'
    | '/admin/tracking'
    | '/courses/$courseId'
    | '/p/$slug'
    | '/topics/$topicId'
    | '/admin/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/activity'
    | '/battle'
    | '/challenge'
    | '/dashboard'
    | '/downloads'
    | '/emergency'
    | '/flashcards'
    | '/games'
    | '/memory'
    | '/notes'
    | '/practice'
    | '/quizzes'
    | '/resources'
    | '/settings'
    | '/todo'
    | '/tracker'
    | '/videos'
    | '/admin/chapters'
    | '/admin/demands'
    | '/admin/events'
    | '/admin/members'
    | '/admin/questions'
    | '/admin/quizzes'
    | '/admin/resources'
    | '/admin/store'
    | '/admin/subjects'
    | '/admin/topics'
    | '/admin/tracking'
    | '/courses/$courseId'
    | '/p/$slug'
    | '/topics/$topicId'
    | '/admin'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/achievements'
    | '/_authenticated/activity'
    | '/_authenticated/battle'
    | '/_authenticated/challenge'
    | '/_authenticated/dashboard'
    | '/_authenticated/downloads'
    | '/_authenticated/emergency'
    | '/_authenticated/flashcards'
    | '/_authenticated/games'
    | '/_authenticated/memory'
    | '/_authenticated/notes'
    | '/_authenticated/practice'
    | '/_authenticated/quizzes'
    | '/_authenticated/resources'
    | '/_authenticated/settings'
    | '/_authenticated/todo'
    | '/_authenticated/tracker'
    | '/_authenticated/videos'
    | '/_authenticated/admin/chapters'
    | '/_authenticated/admin/demands'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/store'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/topics'
    | '/_authenticated/admin/tracking'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/p/$slug'
    | '/_authenticated/topics/$topicId'
    | '/_authenticated/admin/'
    | '/_authenticated/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle': {
      id: '/_authenticated/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AuthenticatedBattleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenge': {
      id: '/_authenticated/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof AuthenticatedChallengeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/todo': {
      id: '/_authenticated/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AuthenticatedTodoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/chapters': {
      id: '/_authenticated/admin/chapters'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AuthenticatedAdminChaptersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/demands': {
      id: '/_authenticated/admin/demands'
      path: '/demands'
      fullPath: '/admin/demands'
      preLoaderRoute: typeof AuthenticatedAdminDemandsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/store': {
      id: '/_authenticated/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AuthenticatedAdminStoreRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/topics': {
      id: '/_authenticated/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AuthenticatedAdminTopicsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tracking': {
      id: '/_authenticated/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AuthenticatedAdminTrackingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$slug': {
      id: '/_authenticated/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof AuthenticatedPSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics/': {
      id: '/_authenticated/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof AuthenticatedTopicsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics/$topicId': {
      id: '/_authenticated/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof AuthenticatedTopicsTopicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminChaptersRoute: typeof AuthenticatedAdminChaptersRoute
  AuthenticatedAdminDemandsRoute: typeof AuthenticatedAdminDemandsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminStoreRoute: typeof AuthenticatedAdminStoreRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminTopicsRoute: typeof AuthenticatedAdminTopicsRoute
  AuthenticatedAdminTrackingRoute: typeof AuthenticatedAdminTrackingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminChaptersRoute: AuthenticatedAdminChaptersRoute,
    AuthenticatedAdminDemandsRoute: AuthenticatedAdminDemandsRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
    AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
    AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRoute,
    AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
    AuthenticatedAdminStoreRoute: AuthenticatedAdminStoreRoute,
    AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
    AuthenticatedAdminTopicsRoute: AuthenticatedAdminTopicsRoute,
    AuthenticatedAdminTrackingRoute: AuthenticatedAdminTrackingRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedBattleRoute: typeof AuthenticatedBattleRoute
  AuthenticatedChallengeRoute: typeof AuthenticatedChallengeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodoRoute: typeof AuthenticatedTodoRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedPSlugRoute: typeof AuthenticatedPSlugRoute
  AuthenticatedTopicsTopicIdRoute: typeof AuthenticatedTopicsTopicIdRoute
  AuthenticatedTopicsIndexRoute: typeof AuthenticatedTopicsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedBattleRoute: AuthenticatedBattleRoute,
  AuthenticatedChallengeRoute: AuthenticatedChallengeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodoRoute: AuthenticatedTodoRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedPSlugRoute: AuthenticatedPSlugRoute,
  AuthenticatedTopicsTopicIdRoute: AuthenticatedTopicsTopicIdRoute,
  AuthenticatedTopicsIndexRoute: AuthenticatedTopicsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
